**Python Libraries**

Python, like other programming languages, has an abundance of additional modules or libraries that augument the base framework and functionality of the language.

Think of a library as a collection of functions that can be accessed to complete certain programming tasks without having to write your own algorithm.

For this course, we will focus primarily on the following libraries:


1.   Numpy is a library for working with arrays of data.
2. Pandas provides high-performance, easy-to-use data structures and data analysis tools.

3. Scipy is a library of techniques for numerical and scientific computing.

4. Matplotlib is a library for making graphs.

5. Seaborn is a higher-level interface to Matplotlib that can be used to simplify many graphing tasks.

6. Statsmodels is a library that implements many statistical techniques.

**NumPy**

NumPy is the fundamental package for scientific computing in Python.
 It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

**Why is NumPy Fast?**

Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code. Vectorized code has many advantages, among which are:

vectorized code is more concise and easier to read

fewer lines of code generally means fewer bugs

the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)

vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.

Broadcasting is the term used to describe the implicit element-by-element behavior of operations; generally speaking, in NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast. Moreover, in the example above, a and b could be multidimensional arrays of the same shape, or a scalar and an array, or even two arrays of with different shapes, provided that the smaller array is “expandable” to the shape of the larger in such a way that the resulting broadcast is unambiguous. 

**Install numpy and other modules on windows**

https://solarianprogrammer.com/2017/02/25/install-numpy-scipy-matplotlib-python-3-windows/

In [1]:
import numpy as np


In [10]:
a = np.arange(15).reshape(3, 5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
print(a.shape)
print(a.ndim)        #no of axes/dimension
print(a.dtype)   
print(a.itemsize)   # size in bytes of each element of the array
print(a.size)
print(type(a))


(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>


In [24]:
np.linspace( 0, 2, 5 )

array([0. , 0.5, 1. , 1.5, 2. ])

**Array from a regular Python list or tuple using the array function**


In [18]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [19]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [20]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [22]:
np.empty( (2,3) )    

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [37]:
A = np.array( [[1,1],[1,3]] )
B = np.array( [[2,0],[3,4]] )
print(A*B)
print(A@B)
print(A.dot(B))

[[ 2  0]
 [ 3 12]]
[[ 5  4]
 [11 12]]
[[ 5  4]
 [11 12]]


In [28]:
rg = np.random.default_rng(1)     # create instance of default random number generator
a = rg.random((2,3))
a

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [29]:
print(a.sum())
print(a.min())
print(a.max())

3.290252281866131
0.14415961271963373
0.9504636963259353


In [38]:
print(A)
A.sum(axis=1) 
A.cumsum(axis=1)   

[[1 1]
 [1 3]]


array([[1, 2],
       [1, 4]])

**Some more ufunc in numpy**



*   exp
*   sqrt
* add etc


